### ISSUE TITLE
Website Kavita connection not saving

### ISSUE THREAD

**Issue by ElryWeeb** [C9Glax/tranga-website#38] opened 2024-01-20 19:47 UTC
on docker latest for api and website.

After entering my kavita details aka http://127.0.0.1:5000 and user + pw and pressing enter or update the entered details just dissapear.
nothing happens...

The tranga website / api logs show nothing happening at all.

**Comment by db-2001** [comment] 2024-01-31 03:49
I'm not sure about the issue overall but if I'm not mistaken, that IP would route the tranga_api container to itself, not to the machine running it (unless you are running the tranga_api container in host networking mode) you'd have to use the actual IP of the host (192.168.X.X or 10.0.0.X whatever it is). You may or may not be able to also use the address of the kavita container inside docker, if they're on the same network - less sure about this method since I don't fully understand docker networking.

**Comment by C9Glax** [comment] 2024-01-31 10:37
Duplicate of https://github.com/C9Glax/tranga/issues/104

**Closed by C9Glax** 2024-01-31 10:37 UTC
